name: Build & Deploy
on: 
    push:
        branches:
        - main
    pull_request: 
        types: 
            - opened
            - synchronize
jobs:
    Build:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - name: Build step
            run: echo "Building the application"
    Deploy:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref_name == 'main'
        steps:
            - name: Deploy step 
              run: echo "Deploying the app"

