name: context variable demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
            echo "This workflow is triggerd by ${{github.actor}}"
            echo "The Repo name is ${{github.repository}}"
