# Context variables provides the information about the current workflows
# https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#secrets-context
name: context variable demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
            echo "This workflow is triggerd by ${{github.actor}}"
            echo "The Repo name is ${{github.repository}}"
            echo "The Branch is ${{github.ref_name}}"
      - name: "print all variables under github"
        run: echo "${{toJson(github)}}"
      - name: "print environment variables"
        run: |
            printenv
            echo "latest commit id is- $GITHUB_SHA"

