# we can use the if condition statement to check weather the steps/jobs should run or not based on some conditions
name: condition Demo
on: 
  push:
    branches:
      - main
      - develop
jobs:
  condition_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main 
        if: github.ref == 'refs/heads/main'
        run: echo " Running if condition step for main branch"
      - name: Run this step
        run: echo "Running this step"




