##  Outputs are values returned by one task which is used by another task 
## Using out put we can share the data between tasks/steps
# Sharing data between jobs

name: Output-Demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        id: step1
        run: echo "version=0.0.1 >> $GITHUB_OUTPUT"
      - name: step two
        run: echo "This version is ${{ steps.step1.outputs.version }}"


    