# secrets in workflows 
#secrets are used to store sensitive information
name: workflow secret
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "hello, ${{ secrets.MY_NAME }}"
