# There are multiple types of trigger 
# 1.Event based trigger # 2. Manual Trigger
# 3. scheduled Trigger # 4. Workflow trigger
#push and pull_request triggers

name: trigger-types
on: 
  push:
    branches:
      - main
      - develop
      - 'relese/**'
  pull_request:
    branches:
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: build step
       run: echo "this is the build step"

