# Variables in workflows 
#Variables are used to store nonsensitive information, Secrets are used to store sensitive data 

name: workflow variables
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "hello, ${{vars.MY_NAME}}"